### PR TITLE
resync GradleProjectInfoTest

### PR DESCRIPTION
**Pull request by dahlstrom-g**
It looks like we solved the same problem different ways. What do you think of this way?

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@dmitry-avdeev

**Comment by dmitry-avdeev** [comment]
Applied, thanks!

**Comment by dahlstrom-g** [comment]
I don't see the commits on [JetBrains:master](https://github.com/JetBrains/android/commits/master) yet.

**Comment by dmitry-avdeev** [comment]
1ffdb3fd6068d6256e086f74e6aadbb7bf209031 ?

**Comment by dahlstrom-g** [comment]
Looks good. Thanks!

**Pull request closed without merging**
