### PR TITLE
Fix jps-plugin resources

### PR DESCRIPTION
**Pull request by garymathews**
- `messages/AndroidJpsBundle.properties` is excluded from `jps-plugin.jar` due to no resource path defined and an incorrect project structure
- Leading to an error when the bundle resource is attempted to be found:
```
Error:Android Dex: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
        ...
```
- This issue has been present since Android Studio 3.0

### CODE REVIEW

**Comment by garymathews** [comment]
@chashnikov

**Comment by chashnikov** [comment]
It looks like the problem was already [reported](https://youtrack.jetbrains.com/issue/IDEA-189170) and [fixed](https://github.com/JetBrains/intellij-community/commit/66e667fdda650fa43a6a6ff480e90739aaba8c9f), it should be fixed in Android Studio 3.3 versions which are based on 182.* builds of IntelliJ platform.

Actually the problem was happened not because AndroidJpsBundle.properties is located under 'src' root (because resource files from sources roots are properly copied to the output by our compiler) and moving it to 'resources' root won't fix it; it was caused by a bug in build scripts which package output files to the JARs.

**Comment by garymathews** [comment]
@chashnikov I don't believe this is fixed. Download Android Studio 3.3 Canary 5 `182.3684` which should contain the fix you referred above (included since `182.1461`).

`android-jps-plugin.jar` is still missing its resources. I believe this PR is still valid, no other module has resources in its `src` directory. That's not where they should go (regardless if the compiler handles this, but my findings suggest it doesn't).

Here's an example of how the bundles are handled in another module: [android/layoutlib](https://github.com/JetBrains/android/tree/master/layoutlib)

**Comment by chashnikov** [comment]
This was fixed in IDEA; if it isn't fixed in Android Studio, it just means that they use different copy of build scripts. The sources of Beta and Canary versions of Android Studio aren't available yet, but in 3.1 there was a separate layout of Android plugin [AndroidStudioProperties.groovy](https://android.googlesource.com/platform/tools/idea/+/studio-3.1.2/build/groovy/org/jetbrains/intellij/build/AndroidStudioProperties.groovy) which is located in their fork of intellij-community repository. Apparently my fix wasn't included into that fork. I'll ask Googlers about that.

If you look at the Android Studio 3.3 files, you'll see that actually AndroidJpsBundle.properties is not missing, it's just included into plugins/android/lib/resources_en.jar, not into android-jps-plugin.jar. This is exactly the problem which was fixed by [my commit](https://github.com/JetBrains/intellij-community/commit/66e667fdda650fa43a6a6ff480e90739aaba8c9f). Your PR is valid indeed, but it won't fix this problem.

**Comment by garymathews** [comment]
@chashnikov Ah, I see. Thanks for investigating! 👍

**Pull request closed without merging**
