### PR TITLE
Revert change to IdeComponents from commit 888a0ac

### PR DESCRIPTION
**Pull request by dahlstrom-g**
This caused NullPointerExceptions in TemplateTest.

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@dmitry-avdeev?

**Comment by dmitry-avdeev** [comment]
Hi Dana, the field has to be cleared to avoid memory leaks. 
I fixed the NPE by checking project for null before registering it. I will create a review for this when it's available in our public repo.

**Comment by dahlstrom-g** [comment]
Thanks! I look forward to cherry-picking that change.

**Comment by dahlstrom-g** [comment]
We've cherry-picked 888a0ac and 212364c. Thanks!

**Pull request closed without merging**
